import Mathlib.Geometry.Convex.Cone.Simplicial


namespace PointedCone

variable {R : Type*} [Field R] [LinearOrder R] [IsStrictOrderedRing R]
variable {G H : Type*}
variable [AddCommGroup G] [Module R G] [AddCommGroup H] [Module R H]

/-- The ray generated by a nonzero vector is simplicial. -/
theorem isSimplicial_hull_singleton (x : G) (hx : x ≠ 0) :
    (hull R {x}).IsSimplicial :=
by
  exact IsSimplicial.hull (Set.finite_singleton x) (LinearIndepOn.singleton hx)

end PointedCone
