import LeanFactory.Sprint.BasisConeCoordinates
import Mathlib.LinearAlgebra.Matrix.ToLin

namespace PointedCone

variable {R : Type*} [CommRing R] [LinearOrder R] [IsStrictOrderedRing R]
variable {M N : Type*} [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]
variable {ι κ : Type*} [Fintype ι] [DecidableEq ι] [Fintype κ]

/-- A linear map sends the cone generated by a source basis into the cone generated by a
codomain basis iff its coordinate matrix in the two named bases is entrywise nonnegative.
Entrywise nonnegativity is written explicitly as `∀ i j, 0 ≤ ... i j`, never as `0 ≤ A`
(which under the scoped `MatrixOrder` instance means positive semidefinite). -/
theorem hull_map_le_iff_toMatrix_nonneg
    (b : Module.Basis ι R M) (c : Module.Basis κ R N) (f : M →ₗ[R] N) :
    (hull R (Set.range b)).map f ≤ hull R (Set.range c) ↔
      ∀ i j, 0 ≤ LinearMap.toMatrix b c f i j :=
by
  constructor
  · intro hle
    intro i j
    rw [LinearMap.toMatrix_apply]
    have hfj : f (b j) ∈ hull R (Set.range c) :=
      hle (by
        rw [PointedCone.mem_map]
        exact ⟨b j, PointedCone.subset_hull ⟨j, rfl⟩, rfl⟩)
    exact (mem_hull_basis_iff c (f (b j))).1 hfj i
  · intro h
    unfold PointedCone.map
    rw [Submodule.map_span_le]
    rintro y ⟨j, rfl⟩
    apply (mem_hull_basis_iff c (f (b j))).2
    intro i
    rw [← LinearMap.toMatrix_apply]
    exact h i j


end PointedCone
