import LeanFactory.Sprint.BasisConeCoordinates
import Mathlib.Geometry.Convex.Cone.TensorProduct
import Mathlib.LinearAlgebra.Dual.Basis

namespace PointedCone

variable {R G : Type*} [CommRing R] [LinearOrder R] [IsStrictOrderedRing R]
variable [AddCommGroup G] [Module R G]

/-- The dual of a basis-generated cone is the cone generated by the dual basis. -/
theorem dual_hull_dualBasis {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b : Module.Basis ι R G) :
    dual (Module.Dual.eval R G) (hull R (Set.range b)) =
      hull R (Set.range b.dualBasis) :=
by
  classical
  rw [dual_hull]
  ext f
  rw [mem_dual, mem_hull_basis_iff b.dualBasis f]
  constructor
  · intro hcoords i
    simpa using hcoords ⟨i, rfl⟩
  · intro hnonneg x hx
    rcases hx with ⟨i, rfl⟩
    simpa using hnonneg i


end PointedCone
