import LeanFactory.Sprint.BasisConeCoordinates
import Mathlib.LinearAlgebra.StdBasis
import Mathlib.Geometry.Convex.Cone.Pointed

namespace PointedCone

variable {R : Type*} [CommRing R] [LinearOrder R] [IsStrictOrderedRing R]
variable {η : Type*} [Fintype η]

/-- The cone generated by the standard basis is the nonnegative orthant.
Smallest explicit finite-coordinate example consuming `PointedCone.mem_hull_basis_iff`;
identifies nonnegative coordinates with the basis-generated cone. -/
theorem hull_stbasis_eq_positive :
    hull R (Set.range (Pi.basisFun R η)) = positive R (η → R) :=
by
  classical
  apply PointedCone.ext
  intro x
  constructor
  · intro hx
    rw [PointedCone.mem_positive]
    intro i
    rw [PointedCone.mem_hull_basis_iff] at hx
    exact (Pi.basisFun_repr R η x i) ▸ hx i
  · intro hx
    rw [PointedCone.mem_hull_basis_iff]
    intro i
    rw [PointedCone.mem_positive] at hx
    exact (Pi.basisFun_repr R η x i).symm ▸ hx i


end PointedCone
